name: Continuous Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Grant execute permission to Gradlew
        run: chmod +x ./backend/gradlew

      - name: Run Integration Tests
        env:
          SPRING_PROFILES_ACTIVE: test
        working-directory: backend
        run: ./gradlew integrationTest

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: backend/build/test-results



#name: Continuous Testing
#
#on:
#  push:
#    branches:
#      - integration_testcases
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      - name: Grant execute permission to gradlew
#        run: chmod +x backend/gradlew
#
#      - name: Set up MySQL service
#        uses: docker/setup-mysql@v1
#        with:
#          mysql-version: '5.7'
#          mysql-root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
#          expose: 3306
#
#      - name: Configure application.properties
#        run: |
#          echo "spring.datasource.url=jdbc:mysql://localhost:3306/dbuser?createDatabaseIfNotExist=true" >> backend/src/test/resources/application-test.properties
#          echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> backend/src/test/resources/application-test.properties
#          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> backend/src/test/resources/application-test.properties
#
#      - name: Run build with Gradle Wrapper
#        working-directory: backend
#        run: ./gradlew build
#
#      - name: Run Integration Tests
#        working-directory: backend
#        run: ./gradlew test --info


#name: Continuous Testing
#
#on:
#  push:
#    branches:
#      - integration_testcases
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      - name: Grant execute permission to gradlew
#        run: chmod +x backend/gradlew
#
#      - name: Set up MySQL service
#        uses: mysql-actions/mysql-start@v2
#        with:
#          mysql-version: '5.7'
#
#      - name: Run build with Gradle Wrapper
#        env:
#          DB_USERNAME: ${{ secrets.DB_USERNAME }}
#          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#        working-directory: backend
#        run: ./gradlew build
#
#      - name: Run Integration Tests
#        env:
#          DB_USERNAME: ${{ secrets.DB_USERNAME }}
#          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#        working-directory: backend
#        run: ./gradlew test --info

