name: Continuous Testing

on:
  push:
    branches:
      - integration_testcases

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Gradle
        uses: gradle/wrapper-action@v1
        with:
          gradle-version: 7.5.1

      - name: Grant execute permission to gradlew
        run: chmod +x backend/gradlew

      - name: Build with Gradle
        working-directory: backend
        run: ./gradlew build

      - name: Run Integration Tests
        working-directory: backend
        run: ./gradlew test 