name: Continuous Testing

on:
  push:
    branches:
      - integration_testcases

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission to gradlew
        run: chmod +x backend/gradlew

      - name: Run build with Gradle Wrapper
        working-directory: backend
        run: ./gradlew build

      - name: Run Integration Tests
        working-directory: backend
        run: ./gradlew test --info
